# Site settings
title: NYPL Digital Repository
email: digpres@nypl.org
description: >
  Documentation for the Digital Repository program at the New York Public Library.
url: "https://nypl.github.io"
baseurl: "/digrepo/docs" # the subpath of your site, e.g. /blog

# Build settings

remote_theme: just-the-docs/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true

ga_tracking: G-2WRB0WJDX7
ga_tracking_anonymize_ip: true
